# =========================================================
# GAUTENG EMS IT SUPPORT
# LOCAL DEVELOPMENT CONFIGURATION
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/ems_it_support
spring.datasource.username=root
spring.datasource.password=Tumelo@04
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# LOCAL EMAIL
# =========================================================

spring.mail.username=gauteng.ems.itsupport@gmail.com
spring.mail.password=lufetwwjyiwgmzwx